#!/bin/bash

#check if the argument is a directory
if [ -d "$1" ]; then
    DIRECTORY="$1"
else
    if [ "$1" = "" ]; then
	echo "The argument is missing!"
    else
	echo "Error! $1 is not a directory!"
	#exiting the script
    fi
    exit
fi

#save current dir to get back to it in the end
PWD=$(pwd)

#go into the given directory
cd "$DIRECTORY" 
echo "$DIRECTORY"

#iterate over all .png and .jpg files in given directory
for i in $(ls | grep -e ".jpg\|.png" ); do
    #get date in form of YYYY-MM-DD Time Timezone
    #the cuts are needed to get rid of the Time and Timezone and DD
    DIRNAME=$(stat -c %y "$DIRECTORY/$i" | cut -d ' ' -f1 | cut -d '-' --fields="1 2")
    #create directory for month YYYY-MM
    #and check if directory already exists
    if ! [ -d "$DIRNAME" ]; then
	mkdir "$DIRNAME"
	#move i, the picture, in the directory of month
    fi
    mv "$i" "$DIRNAME"
done

#go back to dir we started in
cd "$PWD" 
